paths:
  dataset: "dataset"

files:
  supported_types: [".png", ".jpg", ".jpeg"]
  max_resolution: 4098

scraping:
  source: "https://gelbooru.com/index.php?page=dapi&json=1&s=post&q=index&limit=100&tags={}"
  user_agent: "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; Googlebot/2.1; +http://www.google.com/bot.html) Chrome/93.0.4577.83 Safari/537.36"
  limit: 100
  total_limit: 1000
  include_posts_with_parent: true

curation:
  similarity_threshold: 0.985
  model_name: "clip-vit-base32-torch"
  batch_size: 250